/**
 * Generates src/generated/vocabulary.ts and src/generated/meta.ts.
 *
 * The redactor's only knowledge of the FedRAMP schema lives in the generated
 * file: every enum word, the property names whose enum contains "Implemented"
 * (the status keys), the list-of-tests path, and every path the schema
 * defines. Nothing in src/ names a schema key by hand. A new schema revision
 * is a regeneration, not a code change.
 *
 * Usage:
 *   pnpm generate          write the files
 *   pnpm generate:check    exit 1 when the files on disk are stale
 */
import { existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

type Json = Record<string, unknown>;

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SCHEMA_DIR = join(ROOT, 'schemas');
const OUT_DIR = join(ROOT, 'src', 'generated');
const CHECK = process.argv.includes('--check');

const files = readdirSync(SCHEMA_DIR)
  .filter((f) => f.endsWith('.json'))
  .sort();
const docs = new Map<string, Json>();
for (const f of files) {
  const doc = JSON.parse(readFileSync(join(SCHEMA_DIR, f), 'utf8')) as Json;
  docs.set(f, doc);
  if (typeof doc.$id === 'string') docs.set(doc.$id, doc);
}
const mainFile = files.find((f) => f.includes('security-decision-record'));
if (!mainFile) throw new Error('schemas/ has no security-decision-record schema');
const main = docs.get(mainFile)!;
const schemaId = String(main.$id);
const safeUrlPrefix = new URL(schemaId).origin + '/';
const schemaKind = schemaId
  .split('/')
  .pop()!
  .replace(/-schema-\d{4}-\d{2}-\d{2}\.json$/, '');

/** Resolve "#/$defs/x", "<url>#/$defs/x", or "<url>/$defs/x". */
function resolveRef(ref: string, current: Json): { node: Json; doc: Json } {
  let doc = current;
  let pointer = ref;
  if (!ref.startsWith('#')) {
    const i = ref.indexOf('.json');
    if (i < 0) throw new Error(`Unsupported $ref: ${ref}`);
    const url = ref.slice(0, i + 5);
    const rest = ref.slice(i + 5);
    pointer = rest.startsWith('#') ? rest.slice(1) : rest;
    const target = docs.get(url);
    if (!target) throw new Error(`Unknown schema in $ref: ${url}`);
    doc = target;
  } else {
    pointer = ref.slice(1);
  }
  let node: unknown = doc;
  for (const seg of pointer.split('/').filter(Boolean)) {
    if (typeof node !== 'object' || node === null) throw new Error(`Bad pointer: ${ref}`);
    node = (node as Json)[seg];
  }
  if (typeof node !== 'object' || node === null) throw new Error(`Bad pointer: ${ref}`);
  return { node: node as Json, doc };
}

const enumWords = new Map<string, string>();
const statusKeys = new Set<string>();
const paths = new Set<string>();

function lastSegment(path: string): string {
  const i = path.lastIndexOf('.');
  return (i >= 0 ? path.slice(i + 1) : path).replace(/\[\]$/, '');
}

function visit(node: Json, path: string, doc: Json, depth: number): void {
  if (depth > 40) throw new Error(`Schema nesting too deep at ${path}`);
  if (typeof node.$ref === 'string') {
    const r = resolveRef(node.$ref, doc);
    visit(r.node, path, r.doc, depth + 1);
    return;
  }
  if (Array.isArray(node.enum)) {
    for (const w of node.enum) {
      if (typeof w !== 'string') continue;
      const k = w.trim().toLowerCase();
      if (!enumWords.has(k)) enumWords.set(k, w);
      if (w === 'Implemented' && path) statusKeys.add(lastSegment(path));
    }
  }
  const props = node.properties;
  if (props && typeof props === 'object') {
    for (const [k, v] of Object.entries(props as Json)) {
      const p = path ? `${path}.${k}` : k;
      paths.add(p);
      visit(v as Json, p, doc, depth + 1);
    }
  }
  if (node.items && typeof node.items === 'object' && !Array.isArray(node.items)) {
    const p = `${path}[]`;
    paths.add(p);
    visit(node.items as Json, p, doc, depth + 1);
  }
  for (const key of ['allOf', 'anyOf', 'oneOf']) {
    const subs = node[key];
    if (Array.isArray(subs)) for (const sub of subs) visit(sub as Json, path, doc, depth + 1);
  }
}

visit(main, '', main, 0);

// The one path-specific option the tool offers (--keep-test-names) targets the
// schema's list of tests. It is looked up here, from the schema, so src/ never
// spells the key.
const testListPath = [...paths].find((p) => lastSegment(p) === 'ksiTests' && p.endsWith('[]'));
if (!testListPath) throw new Error('Schema has no ksiTests[] path');

const sortedPaths = [...paths].sort();
const sortedEnum = [...enumWords.entries()].sort((a, b) => a[0].localeCompare(b[0]));
const sortedStatus = [...statusKeys].sort();

const header = `// GENERATED by scripts/generate-vocabulary.ts from ${files.join(', ')}.
// DO NOT EDIT. Run \`pnpm generate\` after changing the vendored schemas.
`;

const vocabulary = `${header}
/** The canonical schema URL the redactor was generated from. */
export const SCHEMA_ID = ${JSON.stringify(schemaId)};

/** The vendored schema files this vocabulary reflects. */
export const SCHEMA_FILES: readonly string[] = ${JSON.stringify(files)};

/** Document kind, taken from the schema file name. */
export const SCHEMA_KIND = ${JSON.stringify(schemaKind)};

/** URLs starting with this prefix are FedRAMP's own and are kept. */
export const SAFE_URL_PREFIX = ${JSON.stringify(safeUrlPrefix)};

/** Every enum word in the schema, keyed by its trimmed, lower-cased form. */
export const ENUM_WORDS: Readonly<Record<string, string>> = ${JSON.stringify(Object.fromEntries(sortedEnum), null, 2)};

/** Property names whose enum contains "Implemented": the status keys. */
export const STATUS_KEYS: readonly string[] = ${JSON.stringify(sortedStatus)};

/** The path of the schema's list of tests (the --keep-test-names target). */
export const TEST_LIST_PATH = ${JSON.stringify(testListPath)};

/** Every path pattern the schema defines. Arrays are written as []. */
export const SCHEMA_PATHS: readonly string[] = ${JSON.stringify(sortedPaths, null, 2)};
`;

const pkg = JSON.parse(readFileSync(join(ROOT, 'package.json'), 'utf8')) as { name: string; version: string };
const meta = `// GENERATED by scripts/generate-vocabulary.ts from package.json. DO NOT EDIT.
export const TOOL_NAME = ${JSON.stringify(pkg.name)};
export const TOOL_VERSION = ${JSON.stringify(pkg.version)};
`;

const outputs: Array<[string, string]> = [
  [join(OUT_DIR, 'vocabulary.ts'), vocabulary],
  [join(OUT_DIR, 'meta.ts'), meta],
];

let stale = 0;
for (const [file, content] of outputs) {
  const current = existsSync(file) ? readFileSync(file, 'utf8') : null;
  if (current === content) continue;
  stale += 1;
  if (CHECK) {
    console.error(`stale: ${file}`);
  } else {
    writeFileSync(file, content);
    console.log(`wrote ${file}`);
  }
}
if (CHECK && stale > 0) {
  console.error('Generated files are out of date. Run `pnpm generate` and commit the result.');
  process.exit(1);
}
if (CHECK) console.log('generated files are current');
